# Generated by Django 5.2.7 on 2026-01-27 03:48

import django.db.models.deletion
import upload_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=upload_app.models.upload_to, verbose_name='上传文件')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.IntegerField(verbose_name='文件大小（字节）')),
                ('content_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传列表',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
