# Generated by Django 5.2.7 on 2026-01-27 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], default='INFO', max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('resource_type', models.CharField(blank=True, choices=[('FORM', '表单'), ('USER', '用户'), ('SYSTEM', '系统'), ('OTHER', '其他')], max_length=10, null=True, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='资源ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='操作用户ID')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作IP地址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
